#----------------------------------------------------------------------
# This file was generated by C:\Program Files\Python27\Lib\site-packages\wx-2.8-msw-unicode\wx\tools\img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

logo_2l_32 = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAB3BJ"
    "REFUWIXt131s1dUdx/H373d+D+194PbhXkprWwqUAYoFS9oiUtCpZSSoqKDoNjXOzOmejZnL"
    "lpmSxTi3Zckyt2xZZsKcmWBmZnRqNnlQEYVJ5UEKtK5QLL1tb3tvb++9v9/9PZ790cT9YUxm"
    "dLo/PH+f5Ly+n/M5fxxFUQWf5lI/1dM/A3wG+L8AtF13t3zgR9vlpwYYz1o89tooxgUXytvv"
    "uOMTh6hWICmmB0kJE3Pva2ytSsmWFT2y50vf+EQwSnXXVpmsrWFarWJx/17WTwwxT9U4EImx"
    "t2EZiXkN3NK9lB//8H7lfwL4ybwF8i0EB1tXU160hmBqmMX9e9mUOQPA05rG6ZZV3Nzdxh8e"
    "feRjRyj3R6plk2YCzE69vAe1pgnrX4foOPYCNUJnpuVixPlBWkyTet/H6V7NQ3979mPBKG92"
    "XiknzwzRVy4CkA18fmOYaEuuYNvp3Wiage+7rFBmX+xRGVLrhyRicTJtS/nFS3//SBBVKVlc"
    "0t7JTaKCft9B9z0uDwK++e4b5F2XiFWiXWpkJZxxHNqlRiIW5/D0JOde2c+3utd9pLIq/0y2"
    "yKZIHL9U5GmnwLkwYGm8ipJtU6uoTMmQk6HLBZrBAqmyPygz7Niz+toYQXXIqvwcKiyb4LqN"
    "bH/8jx8qEdUNfPxSkVzg84xT5KK6Bq75fA/bjAhJY7Yba0UFlu/zcGmKWChxkTRF45SuUtG2"
    "VfPGjQ4nkj7imRf4wbzmD5WI+pBRyUGvzJ7QY8CoZFV1Cn00DcAlUmGbEWF/UCbnO9j1CmfX"
    "G+itURZWRLnrWUHtkxmCXEDhazrPb/U4nJjh7khC3ndVz38FUebd9LAsvPVX1OI0XQs62H5y"
    "H63CeG+DJyVPOwXeTpQ5cU0FALUX6ZQGFBpfKnHpaBSAfSmXY58LCKRPzW6Xxs5WzizO0lF3"
    "Nb/96RMfeC3qsq7V1PR8m4pVmzmdG+FxO89Jr4wn/zPAcODy+mUG9953Mx1fThBmoziGS+7e"
    "CE9eE7BTzNA4GlA4XsSI63g3xLHWeQDsH3qOdbct+sA01MG0TeDaKOUCj5YnadYreMTK8Wun"
    "wDuBS3/o8menxPIrklTH5jAnJWi/RaVtc4zMMZf0lMXRmENmfojSqNPcmiTSqDE+lKUyAk0X"
    "V1BSCiz7whz53Qfveh9Ek66Dlx6g4+BTtG+5lY4DB1g/keZl3+HB4iQAl84ziTVJDhWfQUUj"
    "xCdZZ9DQZRIYLqWM4HzHXJY0FBkdHAMgeVEUJy9JD5YQIoqZDPj9ozven0AwdgrtwBOsBYzR"
    "McTUFK3C4DYjxgOxWupQ6MwK+p/LMTFuMVMqU7R9irbPTNojPwR3PrIWc1GR0beKRFMGycVR"
    "ps865M65aLrG0O7ZQcLqFSzcfJ9csG7Te0mIawcO9G4OPOaqOvXpNIYEpESoKkUZouEzZUao"
    "7/N5Y08BWwezQaVcDDn0uzy1C03u2norduMgDWs0ysNR3j2SI/AFuSELPapjTQYsXX0BlTUZ"
    "pjNgR5YTWbym1xo8sF30xlK99aFkh1eiKFSSqkpU1QiBg26Zp1yL+y/fwJWByvJJj9HXXI7u"
    "KZAeg6o9ZVrvqcGo95l00ySiBvHWgFiDTnbIJn3SxKj7Cn7DRibeyRNPjNO6ZhytdBQ7K4k0"
    "XtYrblON3rcTCe5ZtIyZqSl2uEUmCKlSFP7kFmlUBZtWdiLTaerLLmuFSUtBcPzYDFsNk2Or"
    "Fdw5ORQtJAhnY50e8xl53aGq6+fksjnss4fRGtcx43Uxcdxmbv04VY0jZA73Ic5FE703p+po"
    "vXgFC4bfpUsYjIYej9l5NCQb9QipoTOYlgVSEioKUaBC8Xl5OZwe85g4bROda2AmoDyjMLTP"
    "YuD1Jdzw9e/gLFgF8zsoDx3BSZ+COUsZ6ddw0wM4QRKRrG3uvSUMiJ09h3AdTCFYppkU/DJr"
    "VZ2fVVtEbZX5qoYqZr9x50OPXY5F6sE22q+vwxElju8qkDnlgwJHHp8hseZ6mtu6OZWTqJEo"
    "estKzNpm8q/uIEQjkmrDls2I5GVf7F05+CY1nocqBLqiYAU+Z5E8v15nyfdb+UdkmhfHi1SV"
    "BNWh5KXQZWeTw7VfbacqZRLUTdLUGcXO+xzfmWdRj05maiPnqAehEwazpZdeiDIziVTAcRS8"
    "QhaxZXqk95BdYDBwaBA6ehhiA7+0p1FuTbFl00ZKre+gd5q8YJTZM1Hi1WiZJbfHqWxyyYvz"
    "CFXFqFCI1Al8R0FBI9v3JoGjosbmg6YjgxDvzBFyB3fRfef3iK3cQFmJI3514SW93ZZLIQzY"
    "5ZYYdm36ZMCRCpdld9dQiIyA7mImoGaxwYSQ1K5RSPd5yIiLkVBRNUkYSnwXhveXiOuVrLuz"
    "AW96H9lXnse3BIpeTeHgX4hVF4m13UiWSgJfQdxk+71CShqERouqc1b69PsuW5OVDHRKLM/G"
    "ygeUCxK3KMmP+ChKiPQ1Jk46jJ9w0EyNIISx4y4ndhaYv6EC4jbROkFto4vMvEKx70UiyhFi"
    "K64mM1OPX3YIp8f4NwT0a5f7dbOBAAAAAElFTkSuQmCC")
getlogo_2l_32Data = logo_2l_32.GetData
getlogo_2l_32Image = logo_2l_32.GetImage
getlogo_2l_32Bitmap = logo_2l_32.GetBitmap
getlogo_2l_32Icon = logo_2l_32.GetIcon

