from .load_data import PageLoadData
from .stack import PageStack
from .pca import PagePCA
from .pca_cluster import PagePCACluster
from .spectral import PageSpectral
from .cluster import PageCluster
from .peak_id import PagePeakID
from .peak_fitting import PageXrayPeakFitting
from .nnma import PageNNMA
from .tomo import PageTomo
